### ISSUE TITLE
Status 403 (Forbidden)

### ISSUE THREAD

**Issue by witusj** [datacamp/datacamp-light#32]
After creating the html file, and testing it, it states that the session has been disconnected. With a bit of patience and after repeatedly clicking the 'Run' button it finally runs. See this video for a demonstration: https://youtu.be/IFUw7GV6tas

I love the idea behind your tool and if this issue could be resolved, it would be a quantum leap forward for me as a teacher. Truly revolutional!

Update: here's a picture of the inspection field (of another test)

<img width="1379" alt="screen shot 2017-02-05 at 09 33 07" src="https://cloud.githubusercontent.com/assets/5702329/22624885/d56ee236-eb88-11e6-969c-5b7f8a472144.png">

**Comment by filipsch** [comment]
@witusj you might have caught us at a bad time: our session servers were having some difficulties yesterday. Normally this should be resolved by now. Until you've checked, I'll leave this issue open; there might be a bigger problem here!

**Comment by witusj** [comment]
@filipsch I sense a slight improvement (sometimes it works three times in a row), but it is still not very reliable. Here is a [recording](https://youtu.be/jUIsisIMdX4). Good luck and when it works you'll have a big fan. Excellent stuff!

**Comment by filipsch** [comment]
@witusj thanks for these details; I watched the recording and tried to reproduce, but no success. In the inspection field, can you go to the Network tab, and look for XHR commands that are in red. What's the details you see there? They might give more information on the 403 you're getting. Thanks!

**Comment by witusj** [comment]
You'll have to educate me in this matter. Here is what I see:

https://youtu.be/WFODIQWqs9A

![screenshot-2017-feb-06-120-pm](https://cloud.githubusercontent.com/assets/5702329/22647008/6f106590-ec6f-11e6-823a-adcbefb12895.png)
![screenshot-2017-feb-06-119-pm](https://cloud.githubusercontent.com/assets/5702329/22647007/6f0ead68-ec6f-11e6-9497-c2d6e353ab66.png)

**Comment by filipsch** [comment]
Yes, that's close. Now click on one of the red links and tell me what in the 'response' tab for those? Thanks!!

**Comment by witusj** [comment]
It says 'No session'?

https://youtu.be/V-C3jzL7gJs

**Comment by witusj** [comment]
There is always a reason and a solution. You'll fix it. I am not in a hurry.

**Comment by iamarcel** [comment]
@witusj I don't know if this is a backend or front-end error, but you could try with the beta version! (which is all-new and fancy) Clearing your cookies could help too, since we try to remember you when connecting to the backend session. Maybe something went wrong there.

To try the new version, just replace your script tag with this one:

```html
<script type="text/javascript" src="//cdn.datacamp.com/dcl-react.js.gz"></script>
```

**Comment by iamarcel** [comment]
On the page you linked, it looks like the old DataCamp Light is still loaded. Have you tried with the beta version? I added a pull request to update that ;) 

https://github.com/hanbedrijfskunde/onderzoek/pull/1
